app/post/models.py
import enum
from .. import db

class Category(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False, unique = True)
    posts = db.relationship('Posts', backref='category', lazy=True)


class PostType(enum.Enum):
    News = 'News'
    Publication = 'Publication'
    Other = 'Other'



class Posts(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(50), nullable=False)
    text = db.Column(db.Text, nullable=True)
    image_file = db.Column(db.String(20), nullable=False, default='postdefault.jpg')
    created = db.Column(db.DateTime, default=db.func.now())
    type = db.Column(db.Enum(PostType))
    enabled = db.Column(db.Boolean, default=True, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'), nullable=True)


def __repr__(self):
    return f"Posts('{self.id}', '{self.title}', '{self.type}')"

app/post/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField, SubmitField, BooleanField
from wtforms.validators import Length, DataRequired, InputRequired
from flask_wtf.file import FileField, FileAllowed


class PostsForm(FlaskForm):
    title = StringField('Введіть заголовок поста', validators=[InputRequired(), Length(min=2, max=80)])
    text = TextAreaField('Введіть текст поста', validators=[Length(max=2500)])
    picture = FileField('Зображення поста', validators=[FileAllowed(['jpg', 'png'])])
    type = SelectField('Оберіть тип публікації', choices=[('News', 'News'), ('Publication', 'Publication'), ('Other', 'Other')])
    category = SelectField(u'Оберіть категорію', coerce=int)
    enabled = BooleanField('Enabled')
    submit = SubmitField('Підтвердити')

class CategoryPostForm(FlaskForm):
    category_name = StringField('Ввести тип категорії', validators=[DataRequired(message="Це поле обов'язкове"), Length(min=0, max=40)])
    submit = SubmitField('Виконати')

app/post/__init__.py
from flask import Blueprint

posts_blueprint = Blueprint('posts', __name__, template_folder="templates/posts")

from . import views

app/post/views.py
from flask import url_for, render_template, flash, request, redirect, abort, current_app
from .forms import PostsForm, CategoryPostForm
from .models import Posts, Category
from .. import db
from flask_login import login_user, current_user, logout_user, login_required
from . import posts_blueprint
import os
import secrets
from PIL import Image
from datetime import datetime


@posts_blueprint.route('/', methods=['GET', 'POST'])
@login_required
def view_posts():
    form = PostsForm()
    posts = Posts.query.order_by(Posts.title).all()
    return render_template('posts_crud.html', posts_list = posts, form = form, user_id = current_user.id)


@posts_blueprint.route('/create', methods=['GET', 'POST'])
@login_required
def create_post():
    form = PostsForm()
    form.category.choices = [(category.id, category.name) for category in Category.query.all()]
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            image = picture_file
        else:
            image = "postdefault.jpg"
            
        new_post = Posts(title = form.title.data, 
                        text = form.text.data,
                        image_file = image,
                        type = form.type.data,
                        user_id = current_user.id,
                        category_id=form.category.data)

        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for('posts.view_posts'))
    posts = Posts.query.all()
    return render_template('create_post.html', posts = posts, form = form)


@posts_blueprint.route('/<id>', methods=['GET', 'POST'])
def show_post(id):
    print(id)
    post = Posts.query.get_or_404(id)
    category_name = Category.query.get_or_404(post.category_id)
    return render_template('post_details.html', category_name = category_name, post = post)


@posts_blueprint.route('/<id>/delete', methods=['GET', 'POST'])
def delete_post(id):
    post = Posts.query.get_or_404(id)
    if current_user.id == post.user_id:
        db.session.delete(post)
        db.session.commit()
        return redirect(url_for('posts.view_posts'))
    flash('Це не ваш пост', category='warning')
    return redirect(url_for('posts.show_post', id = post.user_id))


@posts_blueprint.route('/<id>/edit', methods=['GET', 'POST'])
def edit_post(id):
    post = Posts.query.get_or_404(id)
    if current_user.id != post.user_id:
        flash('Це договір не є вашим!', category='warning')
        return redirect(url_for('posts.show_post', posts = post, id = id))
    form = PostsForm()
    form.category.choices = [(category.id, category.name) for category in Category.query.all()]
    if form.validate_on_submit():
        post.title = form.title.data
        post.text = form.text.data
        post.type = form.type.data
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            post.image_file = picture_file
        else:
            post.image_file = "postdefault.jpg"
        post.enabled = form.enabled.data
        post.category_id = form.category.data

        db.session.add(post)
        db.session.commit()

        flash('Пост був оновлений', category='access')
        return redirect(url_for('posts.view_posts', id = id))
    form.title.data = post.title 
    form.text.data = post.text
    form.type.data = post.type
    form.enabled.data = post.enabled
    form.category.data = post.category_id

    image_file = url_for("static", filename = "posts_pics/" + post.image_file)
    return render_template('create_post.html', form = form, posts_list = post, image_file = image_file)

def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    f_name, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(current_app.root_path, 'static/posts_pics', picture_fn)
    output_size = (250, 250)

    i = Image.open(form_picture)
    i.thumbnail(output_size)
    i.save(picture_path)

    return picture_fn

@posts_blueprint.route('/categories', methods=['GET', 'POST'])
@login_required
def categories_list():
    form = CategoryPostForm()
    categories = Category.query.order_by(Category.id).all()
    return render_template('categories.html', categories = categories, form = form, user_id = current_user.id)


@posts_blueprint.route('/create_category', methods=['GET', 'POST'])
@login_required
def create_category():
    form = CategoryPostForm()

    if form.validate_on_submit():
        category = Category(name = form.category_name.data)
        db.session.add(category)
        db.session.commit()
        flash('Нова категорія добавлена в таблицю')
        return redirect(url_for('posts.categories_list'))

    categories = Category.query.all()
    return render_template('add_category.html', categories = categories, form = form)


@posts_blueprint.route('<id>/update_category', methods=['GET', 'POST'])
@login_required
def update_category(id):
    category = Category.query.get_or_404(id)
    form = CategoryPostForm()
    if form.validate_on_submit():
        category.name = form.category_name.data

        db.session.add(category)
        db.session.commit()
        flash('Назва категорії була оновлена')
        return redirect(url_for('posts.categories_list'))

    form.category_name.data = category.name
    categories = Category.query.all()
    return render_template('add_category.html', categories = categories, form=form)


@posts_blueprint.route('/<id>/delete_category', methods=['GET'])
@login_required
def delete_category(id):
    category = Category.query.get_or_404(id)
    db.session.delete(category)
    db.session.commit()

    flash('Категорія була вилучена', category='access')
    return redirect(url_for('posts.categories_list'))

app/post/templates/posts/add_category.html
{% from "_render_field.html" import render_field %}
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% from "_render_field.html" import render_field_group, render_field_check, flash_message %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {{ form.csrf_token }}
    <div class="container", style="margin-left: 30%; width: 40%;">
        <div>
            {{ render_field_group(form.category_name) }}
            
            {{ form.submit(class_ ="btn btn-success", style = "margin-top: 20px;") }}
            {{ flash_message() }}
            <a href="{{url_for('posts.categories_list')}}" class="btn btn-primary btn-xs" style = "margin-top: 20px; margin-left: 10px;">Назад</a>
        </div>
    </div>

</form>

{% endblock %}

app/post/templates/posts/categories.html
{% from "_render_field.html" import render_field_group, flash_message %}
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <div class= "align-center">{{ flash_message() }}</div>
    <div class="row">
        <div class="col md-12">
            <div class="jumbotron p-3">
                <h2>Категорії поста
                    <a href = "{{url_for('posts.create_category')}}">
                    <button type="button" class="btn btn-success float-right" data-bs-toggle="modal"
                            data-bs-target="#mymodal">
                        Добавити категорію
                    </button></a>
                </h2>
                <table class="table table-hover table-dark">
                    <tr>
                        <th>ID</th>
                        <th>Категорія</th>
                        <th>Операції</th>
                    </tr>
                    {% for category in categories %}
                    <tr>
                        <td>{{category.id}}</td>
                        <td>{{category.name}}</td>
                        <td>
                            <a href="{{ url_for('posts.update_category', id = category.id) }}"
                               class="btn btn-warning btn-xs">Edit</a>
                            <a href="{{ url_for('posts.delete_category', id = category.id) }}"
                               class="btn btn-danger btn-xs"
                               onclick="return confirm('Are You Sure To Delete ?')">Delete</a>
                        </td>

                    </tr>


                    <!-- Modal Edit Employee-->
                    <div id="modaledit{{category.id}}" class="modal fade" role="dialog">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Змінити тип контракту</h4>
                                </div>
                                <div class="modal-body">
                                    <form action="{{url_for('posts.update_category', id=category.id)}}" method="POST">
                                        {{ form.csrf_token }}
                                        <div class="form-group">
                                            {{ render_field_group(form.category_name) }}
                                        </div>
                                        <div class="form-group">
                                            {{ render_field_group(form.submit) }}
                                        </div>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </table>
            </div>
        </div>

    </div>

</div>
{% endblock %}

app/post/templates/posts/create_post.html
{% from "_render_field.html" import render_field_check, render_field_group, flash_message %}
{% extends 'base.html' %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/style.css') }}">
<div class = "container" style="margin-left: 30%; width: 40%;">
    <div class = "text-center"><h3 >Новий пост</h3></div>
    <form method="POST" enctype="multipart/form-data">
        {{ form.csrf_token }}
        {{ render_field_group(form.title) }}
        {{ render_field_group(form.text) }}
        {{ render_field_group(form.picture) }}
        {{ render_field_group(form.category) }}
        {{ render_field_group(form.type) }}
        {{ render_field_check( form.enabled ) }}
        {{ form.submit(class_ ="btn btn-success", style = "margin-top: 20px;") }}
        {{ flash_message() }}
        <a href="{{url_for('posts.view_posts')}}" class="btn btn-primary btn-xs" style = "margin-top: 20px; margin-left: 10px;">Назад</a>
    </form>
</div>




{% endblock %}

app/post/templates/posts/post_details.html
{% extends 'base.html' %}

{% from "_render_field.html" import render_field_group, flash_message %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
    <div class="content-section align-center" style ="margin-left: 10%; width: 80%; text-align: center;">
        <div class="media">
            <img src="{{ url_for('static', filename='posts_pics/' + post.image_file)  }}">
            <div class="media-body">
                <h2 class="account-heading"> {{ post.title }} </h2>
                <p class="text-secondary"> Категорія поста: {{ category_name.name }} </p>
                <p class="text-secondary">Дата створення поста: {{ post.created.strftime('%d %B %Y - %H:%M:%S') }}</p>
            </div>
        </div>
        <div style = "text-align: center; padding-left: 25%; padding-right: 25%; ">
                <div class="d-flex align-items-start mb-4">
                    <div class="form-outline flex-fill mb-0 center-block">
                        <p>{{ post.text }}</p>
                    </div>
                </div>

                <div class="d-flex flex-row align-items-start mb-4">
                    <div class="form-outline flex-fill mb-0">
                        Тип: {{ post.type.value }}
                    </div>
                </div>
                {% if post.user_id == current_user.id %}
                <div class="d-flex flex-row align-items-center mb-4">
                    <div class="form-outline flex-fill mb-0">
                        <a href="{{url_for('posts.edit_post', id = post.id)}}" class="btn btn-warning btn-xs">Edit</a>
                        <a href="{{url_for('posts.delete_post', id = post.id)}}" class="btn btn-danger btn-xs" onclick="return confirm('Are You Sure To Delete ?')">Delete</a>
                        {% else %}
                            <h5 style="color: red;">Це не ваш пост. Редагування чи видалення неможливе.</h5>
                        
                        
                    {% endif %}
                    <a href="{{ url_for('posts.view_posts', id = current_user.id) }}">
                        <p class="btn btn-primary btn-xs" style = "margin-top: 17px">Back</p>
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/post/templates/posts/posts_crud.html
{% extends 'base.html' %}

{% from "_render_field.html" import render_field_group, render_field_check, flash_message %}

{% block content %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
<div class="container">
    <div class="row">
        <span class = "main">
            <h2>Пости</h2>
            <a href="{{url_for('posts.create_post')}}"><button type="button"  class="btn btn-success float-right">Add new post</button> </a>
        </span>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-success alert-dismissable" role="alert">
                    {{message}}
                </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        {% for post in posts_list %}
        <div class="col-md-4     my_padding">
            <div class="my_block">
                <div class="text-center">
                    <img src="{{ url_for('static', filename='posts_pics/' + post.image_file) }}">
                </div>
                <div class="blog-content">
                    <h4><a href="{{ url_for('posts.show_post', id= post.id) }}">{{ post.title }}</a></h4>
                    <div class="btn-group btn-toggle">
                        
                            <b>{{ 'Enabled' if post.enabled else 'Disabled' }}</b>
                    </div>
                    <p>{{ post.type.value }}</p>
                    <p>{{ post.text[:100] + '...' }}</p>
                    <div class="btn-group btn-toggle">
                        <a href="{{url_for('posts.show_post',  id = post.id  )}}" class="btn btn-round btn-info">View More</a>
                    </div>
                </div>
                <span class="blog-date">Created: {{ post.created.strftime('%m/%d/%Y - %H:%M') }}</span>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}