app/form_cabinet/forms.py
from wtforms import StringField, PasswordField, SubmitField, SelectField
from wtforms.validators import ValidationError, InputRequired, Length, AnyOf
from flask_wtf import FlaskForm
from re import match
from email_validator import validate_email, EmailSyntaxError

class LoginForm(FlaskForm):
    username = StringField('username', validators=[InputRequired('A username is required!'), 
                            Length(min=5, max=10, message='Must be from 5 to 10 symbols')])
    password = PasswordField('password', validators=[InputRequired('Password is required!'), 
                            AnyOf(values=['password', 'secret'])])


class RegistrationForm(FlaskForm):
    login = StringField("Логін (адреса електронної пошти)*")
    password = PasswordField("Пароль *")
    confirm_password = PasswordField("Підтвердження паролю")
    number = StringField("Номер *")
    pin = StringField("Пін *")
    year = SelectField("Рік *", choices=range(1980, 2022))
    diplom_serial = StringField("Серія")
    diplom_number = StringField("Номер *")
    submit = SubmitField("Зареєструвати")

    def validate_login(self, login):
        user_login = self.login.data
        if user_login is None:
            raise ValidationError("Це поле має бути обов'язкове")
        else:
            try:
                validate_email(user_login)
            except EmailSyntaxError:
                raise ValidationError("Неправильно введена електронна пошта!")


    def validate_password(self, password):
        user_password = self.password.data
        if user_password is None:
            raise ValidationError("Це поле має бути обов'язкове")
        elif len(user_password) < 6:
            raise ValidationError("Пароль мусить бути не менше 6 символів")

    def validate_confirm_password(self, confirm_password):
        if self.confirm_password.data is None:
            raise ValidationError("Це поле має бути обов'язкове")
        elif self.password.data != self.confirm_password.data:
            raise ValidationError("Паролі не співпадають")

    def validate_number(self, number):
        user_num = self.number.data
        if match(r"^[0-9]{7}$", user_num) is None:
            raise ValidationError("Поле повинно містити строго 7 цифр")
        elif user_num is None:
            raise ValidationError("Це поле має бути обов'язкове")

    def validate_pin(self, pin):
        user_pin = self.pin.data
        if match(r"^[0-9]{4}$", user_pin) is None:
            raise ValidationError("Поле повинно містити строго 4 цифр")
        elif user_pin is None:
            raise ValidationError("Це поле має бути обов'язкове")

    def validate_diplom_serial(self, diplom_serial):
        user_diplom_serial = self.diplom_serial.data
        if self.year.data < "2015":
            if match(r"^[A-Z]{2}$", user_diplom_serial) is None:
                raise ValidationError("Серія диплому повинна складатись з двох латинських літер!")
        else:
            if match(r"^[A-Z]{1}[0-9]{2}$", user_diplom_serial) is None:
                raise ValidationError("Серія диплому повинна складатись з однієї латинських літер та двох цифр!")

    def validate_diplom_number(self, diplom_number):
        user_diplom_number = self.diplom_number.data
        if self.year.data < "2015":
            if match(r"^[0-9]{8}$", user_diplom_number) is None:
                raise ValidationError("Номер диплому повинен складатись з 8 цифр!")
            elif user_diplom_number is None:
                raise ValidationError("Це поле має бути обов'язкове")
        else:
            if match(r"^[0-9]{6}$", user_diplom_number) is None:
                raise ValidationError("Номер диплому повинен складатись з 6 цифр!")
            elif user_diplom_number is None:
                raise ValidationError("Це поле має бути обов'язкове")
    

app/form_cabinet/__init__.py
from flask import Blueprint, render_template, abort
from jinja2 import TemplateNotFound

form_cabinet_blueprint = Blueprint('form_cabinet', __name__, template_folder="templates/form_cabinet")

from . import views

app/form_cabinet/views.py
from flask import render_template, url_for, flash, redirect, request, session
from flask_bootstrap import Bootstrap
from .. import bootstrap
from json import load, dump, decoder
from .forms import LoginForm, RegistrationForm

from . import form_cabinet_blueprint

def add_info(validate):
    dictionary = {}
    data = {
        validate.login.data: { "password" : validate.password.data, "number_e" : validate.number.data,
            "pin_e" : validate.pin.data,
            "year_of_receive": validate.year.data,
            "diplom_serial": validate.diplom_serial.data,
            "diplom_number" : validate.diplom_number.data
        }
    }
    try:
        with open("registers.json", "r") as file:
            dictionary = load(file)
            dictionary.update(data)

        with open("registers.json", "w", encoding="utf-8") as write_file:
            dump(dictionary, write_file, ensure_ascii = False, indent = 4)

    except FileNotFoundError or decoder.JSONDecodeError:
        with open("registers.json", "w", encoding="utf-8") as write_file:
            dump(data, write_file, ensure_ascii = False, indent = 4)

@form_cabinet_blueprint.route('/basic_form', methods=['GET', 'POST'])
def basic_form():
    form = LoginForm()
    if form.validate_on_submit():
        flash('Дані занесені успішно!')
        flash('The username is ' + form.username.data + ". The password is " + form.password.name + "!")
        return redirect(url_for('form_cabinet.basic_form'))
    return render_template('basic_form.html', form=form)

@form_cabinet_blueprint.route('/form_cabinet', methods=['GET', 'POST'])
def form_cabinet():
    form = RegistrationForm()
    if form.validate_on_submit():
        flash('Дані занесені успішно!')
        add_info(form)
        session['login'] = form.login.data
        session['number'] = form.number.data
        session['pin'] = form.pin.data
        session['year'] = form.year.data
        session['diplom_serial'] = form.diplom_serial.data
        session['diplom_number'] = form.diplom_number.data
        return render_template('form_cabinet.html', 
                            form=form,
                            login=session.get("login"),
                            number=session.get("number"),
                            pin=session.get("pin"),
                            year=session.get("year"),
                            diplom_serial=session.get("diplom_serial"),
                            diplom_number=session.get("diplom_number"),)
    elif not form.validate_on_submit():
        flash('Дані не було внесено!')
    return render_template('form_cabinet.html', 
                            form=form,
                            login=session.get("login"),
                            number=session.get("number"),
                            pin=session.get("pin"),
                            year=session.get("year"),
                            diplom_serial=session.get("diplom_serial"),
                            diplom_number=session.get("diplom_number"),)

app/form_cabinet/templates/form_cabinet/basic_form.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% from "_render_field.html" import render_field_basic_form %}

{% block content %} 
        <div class = "container text-center">
            <h1>Out form will be here!</h1>
            <form method="POST" action="{{ url_for('form_cabinet.basic_form')}}">
                {{ form.csrf_token }}
                {{ render_field_basic_form(form.username)}}
                {{ render_field_basic_form(form.password)}}
                <input type = "submit" value = "Submit">
            </form>
        </div>
{% endblock %}

app/form_cabinet/templates/form_cabinet/form_cabinet.html
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% from "_render_field.html" import render_field_cabinet_form, flash_message %}

{% block content %} 
        <span class = "text-center" style="color: rgb(66, 66, 150);">
            <h1>Реєстрація особистого електронного кабінету</h1>
        </span>
        <div class = "container">
            <form method="POST" action="{{ url_for('form_cabinet.form_cabinet')}}">
                {{ form.csrf_token }}
                
                {{ render_field_cabinet_form( form.login, class_label="col-sm-3" )}}
                {{ render_field_cabinet_form( form.password, class_label="col-sm-3" )}}
                {{ render_field_cabinet_form( form.confirm_password, class_label="col-sm-3" )}}

                <h3 style="color: rgb(66, 66, 150);">Екзаменаційний лист (сертифікат) ЗНО магістра</h3> 
                {{ render_field_cabinet_form( form.number, class_label="col-sm-2" )}}
                {{ render_field_cabinet_form( form.pin, class_label="col-sm-2" )}}
                {{ render_field_cabinet_form( form.year, class_label="col-sm-2" )}}
                
                <h3 style="color: rgb(66, 66, 150);">Документ про освіту</h3>
                {{ render_field_cabinet_form( form.diplom_serial, class_label="col-sm-3" )}}
                {{ render_field_cabinet_form( form.diplom_number, class_label="col-sm-3" )}}

                <input type = "submit" value = "Зареєструвати" class="form-control btn btn-primary mb-2 float-right">
            </form>
            {{ flash_message() }}
        </div>
{% endblock %}