app/contract_activities/models.py
import enum
from .. import db


"""class ContractTypes(enum.Enum):
    one_sided = "Односторонній"
    two_sided = "Двохсторонній"
    many_sided = "Багатосторонній"""

class Contractypes(db.Model):
    type_id = db.Column(db.Integer, primary_key=True)
    type = db.Column(db.String(50), nullable=False, unique = True)
    contract = db.relationship('Contracts', backref='my_backref_types', lazy=True)


class Contracts(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    contract_code = db.Column(db.String(10), nullable=False, unique=True)
    organization_name = db.Column(db.String(50), nullable=False)
    deadline = db.Column(db.Date(), nullable=False)
    contract_amount = db.Column(db.Float(), nullable=True)
    contract_type = db.Column(db.Integer, db.ForeignKey('contractypes.type_id'), nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __repr__(self):
        return f"Сontracts('{self.id}', '{self.organization_name}')"

app/contract_activities/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField, FloatField
from wtforms.fields.html5 import DateField
from wtforms.validators import Length, DataRequired, InputRequired, Required, Regexp
from .models import Contractypes


class ContractForm(FlaskForm):
    contract_code = StringField("Шифр договору",validators=[
                        InputRequired(message="Це поле обов'язкове"),
                        Regexp(r'^[A-Z]{3}-[0-9]{4}$', 0,
                        message="Шифр договору повинен складатись з трьох латинських великих літер, дефізу і чотирьох цифр")], )
    organization_name = StringField('Найменування організації', 
                        validators=[InputRequired(message="Це поле обов'язкове"), 
                        Length(max=100, message="Поле має мати не більше ста символів")])
    deadline = DateField('Термін виконання', format="%Y-%m-%d",
                            validators=[Required(message="Це поле обов'язкове")])
    contract_amount = StringField('Cума договору', 
                    validators=[
                    DataRequired(message="Це поле обов'язкове"),
                    Regexp(r'[0-9]*\.[0-9]{2}$', 0,
                    message="Сума повинна мати дробове значення дві цифри після коми")])
    contract_type = SelectField('Оберіть категорію', coerce = int)
    submit = SubmitField('Добавити договір')


class CategoryForm(FlaskForm):
    contract_type = StringField('Ввести тип категорії', validators=[DataRequired(message="Це поле обов'язкове"), Length(min=0, max=40)])
    submit = SubmitField('Виконати')

app/contract_activities/__init__.py
from flask import Blueprint

contract_activities_blueprint = Blueprint('contracts', __name__, template_folder="templates/contract_activities")

from . import views

app/contract_activities/views.py
from flask import url_for, render_template, flash, request, redirect, abort, current_app
from .forms import ContractForm, CategoryForm
from .models import Contracts, Contractypes
from .. import db
from flask_login import login_user, current_user, logout_user, login_required
from . import contract_activities_blueprint
from datetime import datetime


@contract_activities_blueprint.route('/', methods=['GET', 'POST'])
@login_required
def view_contract_info():
    form = ContractForm()
    contracts = Contracts.query.order_by(Contracts.deadline).all()
    return render_template('crud_contracts.html', contracts_list = contracts, form = form, user_id = current_user.id)


@contract_activities_blueprint.route('/add_contract', methods=['GET', 'POST'])
@login_required
def new_contract():
    form = ContractForm()
    form.contract_type.choices = [(type_c.type_id, type_c.type) for type_c in Contractypes.query.all()]
    if form.validate_on_submit():
        contract_data = Contracts(contract_code = form.contract_code.data, 
                            organization_name = form.organization_name.data,
                            deadline = form.deadline.data,
                            contract_amount = form.contract_amount.data,
                            contract_type = form.contract_type.data,
                            user_id = current_user.id)

        db.session.add(contract_data)
        db.session.commit()
        return redirect(url_for('contracts.view_contract_info'))
    contracts = Contracts.query.order_by(Contracts.contract_code).all()
    return render_template('new_contract_add.html', contracts_list = contracts, form = form)


@contract_activities_blueprint.route('/<id>', methods=['GET', 'POST'])
def detail_info_contract(id):
    print(id)
    contracts = Contracts.query.get_or_404(id)
    contract_type = Contractypes.query.get_or_404(contracts.contract_type)
    print(contract_type)
    return render_template('contract_full_info.html', contract = contracts, contract_type = contract_type)


@contract_activities_blueprint.route('/<id>/delete_contract', methods=['GET', 'POST'])
def delete_contract(id):
    contract = Contracts.query.get_or_404(id)
    if current_user.id == contract.user_id:
        db.session.delete(contract)
        db.session.commit()
        return redirect(url_for('contracts.view_contract_info'))
    flash('Це не ваш пост', category='warning')
    return redirect(url_for('contracts.detail_info_contract', id=contract.user_id))


@contract_activities_blueprint.route('/<id>/edit_contract', methods=['GET', 'POST'])
def edit_contract(id):
    contract = Contracts.query.get_or_404(id)
    if current_user.id != contract.user_id:
        flash('Це договір не є вашим!', category='warning')
        return redirect(url_for('contracts.detail_info_contract', contracts = contract, id = id))
    form = ContractForm()
    form.contract_type.choices = [(contract.type_id, contract.type) for contract in Contractypes.query.all()]
    if form.validate_on_submit():
        contract.organization_name = form.organization_name.data
        contract.contract_code = form.contract_code.data
        contract.deadline = form.deadline.data
        contract.contract_amount = form.contract_amount.data
        contract.contract_type = form.contract_type.data

        db.session.add(contract)
        db.session.commit()

        flash('Договір був оновлений', category='access')
        return redirect(url_for('contracts.detail_info_contract', id=id))
    contract.organization_name = form.organization_name.data
    contract.contract_code = form.contract_code.data
    contract.deadline = form.deadline.data
    contract.contract_amount = form.contract_amount.data
    contract.contract_type = form.contract_type.data

    return render_template('new_contract_add.html', form=form, contracts_list = contract)

@contract_activities_blueprint.route('/contract_types', methods=['GET', 'POST'])
@login_required
def contract_types_info():
    form = CategoryForm()
    types = Contractypes.query.order_by(Contractypes.type_id).all()
    return render_template('contract_types.html', contract_types = types, form = form, user_id = current_user.id)


@contract_activities_blueprint.route('/add_contract_type', methods=['GET', 'POST'])
@login_required
def contract_type_add():
    form = CategoryForm()

    if form.validate_on_submit():
        contract_type = Contractypes(type = form.contract_type.data)

        db.session.add(contract_type)
        db.session.commit()
        flash('Добавлений новий тип договору')
        return redirect(url_for('contracts.contract_types_info'))

    contract_types = Contractypes.query.all()
    return render_template('add_contract_type.html', contract_types=contract_types, form=form)


@contract_activities_blueprint.route('<id>/update_contract_type/', methods=['GET', 'POST'])
@login_required
def update_contract_type(id):
    contract_type = Contractypes.query.get_or_404(id)
    form = CategoryForm()
    if form.validate_on_submit():
        contract_type.type = form.contract_type.data

        db.session.add(contract_type)
        db.session.commit()
        flash('Тип договору оновлений')
        return redirect(url_for('contracts.contract_types_info'))

    form.contract_type.data = contract_type.type
    contract_types = Contractypes.query.all()
    return render_template('add_contract_type.html', contract_types = contract_types, form=form)


@contract_activities_blueprint.route('/<id>/delete_contract_type', methods=['GET'])
@login_required
def delete_contract_type(id):
    contract_type = Contractypes.query.get_or_404(id)
    db.session.delete(contract_type)
    db.session.commit()

    flash('Тип договору вилучено', category='access')
    return redirect(url_for('contracts.contract_types_info'))

app/contract_activities/templates/contract_activities/add_contract_type.html
{% from "_render_field.html" import render_field %}
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% from "_render_field.html" import render_field_group, render_field_check, flash_message %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {{ form.csrf_token }}
    <div class="container", style="margin-left: 30%; width: 40%;">
        <div>
            {{ render_field_group(form.contract_type) }}
            
            {{ form.submit(class_ ="btn btn-success", style = "margin-top: 20px;") }}
            {{ flash_message() }}
            <a href="{{url_for('contracts.contract_types_info')}}" class="btn btn-primary btn-xs" style = "margin-top: 20px; margin-left: 10px;">Назад</a>
        </div>
    </div>

</form>

{% endblock %}

app/contract_activities/templates/contract_activities/contract_full_info.html
{% from "_render_field.html" import render_field %}
{% extends 'base.html' %}
{% block content %}
<div class = "container">
        <div class="text-center">
            <p>Договір {{ contract.contract_code }}</p>
            <hr>
            <p>Назва організації: {{ contract.organization_name }}</p>
            <p>Термін виконання: {{ contract.deadline.strftime('%B %d %Y') }}</p>
            <p>Вартість договору: {{ contract.contract_amount }}</p>
            <p>Тип категорії: {{ contract_type.type }}</p>
        </div>
        <div class="buttons text-center">
            {% if current_user.id == contract.user_id %}
            <a href = "{{ url_for('contracts.delete_contract', id = contract.id)}}"">
            <button type="button" class="btn btn-danger">
                Delete
            </button></a>
            <a href="{{ url_for('contracts.edit_contract', id = contract.id) }}"> <!-- edit !-->
                <button class="btn btn-warning">Edit</button>
            </a>
            {% else %}
                <h5 style="color: red;">Це не ваш договір. Редагування чи видалення неможливе.</h5>
            {% endif %}
            <a href="{{ url_for('contracts.view_contract_info', id = contract.id) }}"> <!-- edit !-->
                <button class="btn btn-primary">Back</button>
            </a>
        </div>
    </div>
</div>
{% endblock %}

app/contract_activities/templates/contract_activities/contract_types.html
{% from "_render_field.html" import render_field_group, flash_message %}
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <div class= "align-center">{{ flash_message() }}</div>
    <div class="row">
        <div class="col md-12">
            <div class="jumbotron p-3">
                <h2>Управління <b>Типи контрактів </b>
                    <a href = "{{url_for('contracts.contract_type_add')}}">
                    <button type="button" class="btn btn-success float-right" data-bs-toggle="modal"
                            data-bs-target="#mymodal">
                        Добавити новий тип контракту
                    </button></a>
                </h2>
                <table class="table table-hover table-dark">
                    <tr>
                        <th>ID</th>
                        <th>Вид договору</th>
                        <th>Операції</th>
                    </tr>
                    {% for type in contract_types %}
                    <tr>
                        <td>{{type.type_id}}</td>
                        <td>{{type.type}}</td>
                        <td>
                            <a href="{{ url_for('contracts.update_contract_type', id = type.type_id) }}"
                               class="btn btn-warning btn-xs">Edit</a>
                            <a href="{{ url_for('contracts.delete_contract_type', id = type.type_id) }}"
                               class="btn btn-danger btn-xs"
                               onclick="return confirm('Are You Sure To Delete ?')">Delete</a>
                        </td>

                    </tr>


                    <!-- Modal Edit Employee-->
                    <div id="modaledit{{type.type_id}}" class="modal fade" role="dialog">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Змінити тип контракту</h4>
                                </div>
                                <div class="modal-body">
                                    <form action="{{url_for('contracts.update_contract_type', id=type.type_id)}}" method="POST">
                                        {{ form.csrf_token }}
                                        <div class="form-group">
                                            {{ render_field_group(form.contract_type) }}
                                        </div>
                                        <div class="form-group">
                                            {{ render_field_group(form.submit) }}
                                        </div>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </table>
            </div>
        </div>

    </div>

</div>
{% endblock %}

app/contract_activities/templates/contract_activities/crud_contracts.html
{% extends 'base.html' %}

{% from "_render_field.html" import render_field_group, render_field_check, flash_message %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col md-12">
            <div class="jumbotron p-3">
                <h2>Керувати <b>Договора організацій </b>  <a href="{{url_for('contracts.new_contract')}}"><button type="button"  class="btn btn-success float-right">Добавити новий контракт</button> </a></h2>
                {% with messages = get_flashed_messages() %}
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-success alert-dismissable" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">x</span>
                    </button>
                {{message}}
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}
                <table class="table table-hover table-dark">
                    <tr>
                        <th>ID</th>
                        <th>Шифр договору</th>
                        <th>Назва організації</th>
                        <th>Дедлайн</th>
                        <th>Action</th>
                    </tr>
                   {% for contract in contracts_list %}
                    <tr>
                        <td>{{contract.id}}</td>
                        <td>{{contract.contract_code}}</td>
                        <td>{{contract.organization_name}}</td>
                        <td>{{contract.deadline}}</td>
                        <td>
                            
                            <a href="{{url_for('contracts.detail_info_contract', id = contract.id)}}" class="btn btn-primary btn-xs">Info</a>
                            <a href="{{url_for('contracts.edit_contract', id = contract.id)}}" class="btn btn-warning btn-xs">Edit</a>
                            <a href="{{url_for('contracts.delete_contract', id = contract.id)}}" class="btn btn-danger btn-xs" onclick="return confirm('Are You Sure To Delete ?')">Delete</a>
                        </td>
                    </tr>


                  <!-- Modal Edit Employee-->
                    
                </div>
            </div>
            {% endfor %}
        </table>
        </div>
    </div>
</div>

{% endblock %}

app/contract_activities/templates/contract_activities/new_contract_add.html
{% from "_render_field.html" import render_field %}
{% extends 'base.html' %}

{% block title %} {{ title }} {% endblock %}

{% from "_render_field.html" import render_field_group, render_field_check, flash_message %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {{ form.csrf_token }}
    <div class="container", style="margin-left: 30%; width: 40%;">
        <div>
            {{ render_field_group(form.organization_name) }}
            {{ render_field_group(form.contract_code) }}
            {{ render_field_group(form.deadline) }}
            {{ render_field_group(form.contract_amount) }}
            {{ render_field_group(form.contract_type) }}
            {{ form.submit(class_ ="btn btn-success", style = "margin-top: 20px;") }}
            {{ flash_message() }}
            <a href="{{url_for('contracts.view_contract_info')}}" class="btn btn-primary btn-xs" style = "margin-top: 20px; margin-left: 10px;">Назад</a>
        </div>
    </div>

</form>

{% endblock %}